import Image from "next/image";

const groupUrl = "https://www.facebook.com/groups/960994296456160";

export default function Home(){return <>
  <header className="site-header"><a href="#top" className="mini-brand">Veritas <span>Village</span></a><nav aria-label="Main navigation"><a href="#welcome">Welcome</a><a href="#families">Families</a><a href="#rhythm">Our rhythm</a><a href="#resources">Resources</a></nav><a className="header-link" href={groupUrl} target="_blank" rel="noreferrer">Connect with us</a><details><summary>Menu</summary><div><a href="#welcome">Welcome</a><a href="#families">Families</a><a href="#rhythm">Our rhythm</a><a href="#resources">Resources</a><a href={groupUrl}>Connect with us</a></div></details></header>

  <main id="top">
    <section className="hero"><div className="hero-logo"><Image src="/veritas-approved-lockup.png" alt="Veritas Village" width={1536} height={1024} priority/></div><p className="descriptor">A Central Texas homeschool co-op</p><h1>Learning in truth.<br/><em>Growing in community.</em></h1><p className="hero-copy">A welcoming place for families to learn alongside one another—rooted close to home and open to a wide world of wonder.</p><a className="primary-link" href={groupUrl} target="_blank" rel="noreferrer">Meet the village <span>→</span></a><div className="scroll-note">Scroll to wander <i>↓</i></div></section>

    <section id="welcome" className="welcome"><div className="welcome-title"><span>Welcome</span><h2>There is room<br/>at the table.</h2></div><div className="welcome-copy"><p className="lead">Veritas Village is a shared place for homeschool families to learn with intention and belong with ease.</p><p>We gather around books, questions, projects, and the everyday work of learning. Children find companions for discovery. Parents find encouragement, shared wisdom, and people who understand the road.</p><p>Nothing polished for show. Just real families bringing what they know, staying curious, and growing together.</p></div><div className="welcome-mark" aria-hidden="true">V</div></section>

    <section className="motto"><p>Grounded</p><i>◆</i><p>Curious</p><i>◆</i><p>Gracious</p><i>◆</i><p>Locally rooted</p></section>

    <section id="families" className="families"><div className="families-copy"><p className="eyebrow">For families</p><h2>Come curious.<br/>Bring what you know.</h2><p>A healthy co-op is shaped by the people inside it. Families learn, contribute, ask for help, and make room for one another.</p><p>Current enrollment, class choices, expectations, and welcome steps are shared personally with interested families.</p><a className="text-link" href={groupUrl} target="_blank" rel="noreferrer">Start a conversation →</a></div><div className="family-panel"><Image src="/veritas-approved-lockup.png" alt="" width={1536} height={1024}/><blockquote>“A place where families learn in truth and grow in community.”</blockquote></div></section>

    <section id="rhythm" className="rhythm"><div className="rhythm-heading"><p className="eyebrow">Our shared rhythm</p><h2>A year made of small,<br/><em>meaningful moments.</em></h2></div><div className="rhythm-flow"><article><span>01</span><h3>Gather</h3><p>Arrive, settle in, and make room for conversation and friendship.</p></article><article><span>02</span><h3>Learn</h3><p>Follow ideas through reading, discussion, nature, projects, and creative work.</p></article><article><span>03</span><h3>Share</h3><p>Offer what you know and receive the experience of other families.</p></article><article><span>04</span><h3>Grow</h3><p>Leave with new questions, deeper confidence, and people beside you.</p></article></div><div className="calendar-note"><strong>2026–27 calendar</strong><p>Current dates, class days, and locations stay in the private group so family information remains protected.</p><a href={groupUrl} target="_blank" rel="noreferrer">View current events →</a></div></section>

    <section id="resources" className="resources"><div><p className="eyebrow">The shared shelf</p><h2>Made useful.<br/>Kept together.</h2><p>Participating families receive access to the co-op’s working materials in the shared Drive.</p></div><ul><li><span>Curriculum</span><small>Planning and class materials</small></li><li><span>Family guides</span><small>Expectations and practical information</small></li><li><span>Schedules</span><small>Calendars and event details</small></li><li><span>Community resources</span><small>Helpful links shared by parents</small></li></ul></section>

    <section className="invitation"><Image src="/veritas-approved-lockup.png" alt="Veritas Village" width={1536} height={1024}/><p>Rooted in Central Texas. Open to wonder.</p><h2>Come as you are.</h2><a href={groupUrl} target="_blank" rel="noreferrer">Connect with Veritas Village →</a></section>
  </main>
  <footer><span>Veritas Village</span><span>Learning in truth. Growing in community.</span><span>Central Texas</span></footer>
  </>}
