import Image from "next/image";

const facebookUrl = "https://www.facebook.com/groups/960994296456160";

function Brand() {
  return <a className="brand" href="#top" aria-label="Veritas Village home"><Image src="/veritas-mark.png" alt="" width={54} height={54} priority /><span>Veritas Village<small>A Central Texas homeschool co-op</small></span></a>;
}

export default function Home() {
  return <>
    <header className="site-header"><Brand /><nav className="desktop-nav" aria-label="Main navigation"><a href="#about">About</a><a href="#families">Families</a><a href="#calendar">Calendar</a><a href="#resources">Resources</a><a className="button small" href={facebookUrl} target="_blank" rel="noreferrer">Join the conversation</a></nav><details className="mobile-nav"><summary aria-label="Open navigation">Menu</summary><nav><a href="#about">About</a><a href="#families">Families</a><a href="#calendar">Calendar</a><a href="#resources">Resources</a><a href={facebookUrl}>Facebook group</a></nav></details></header>
    <main id="top">
      <section className="hero section-shell"><div className="hero-copy"><p className="eyebrow">Rooted in Central Texas</p><h1>Learning in truth.<br/><em>Growing in community.</em></h1><p className="lede">A shared place for homeschool families to learn with intention, ask good questions, and belong with ease.</p><div className="actions"><a className="button" href={facebookUrl} target="_blank" rel="noreferrer">Visit our Facebook group</a><a className="text-link" href="#about">Discover the village <span>→</span></a></div></div><div className="hero-art" aria-hidden="true"><div className="sun"/><Image src="/veritas-feather.png" alt="" width={510} height={540} priority /></div></section>
      <section id="about" className="welcome section-shell"><div><p className="eyebrow">Welcome to the village</p><h2>A place to learn alongside one another.</h2></div><div className="welcome-copy"><p>Veritas Village is a Central Texas homeschool co-op shaped by families who value curiosity, shared work, and generous community.</p><p>Here, education is more than a schedule. It is books opened together, projects taking shape around a table, questions carried outdoors, and parents encouraging one another along the way.</p></div></section>
      <section className="values" aria-label="Our community values"><article><span>01</span><h3>Gather</h3><p>Make room for friendship, conversation, and unhurried Texas hospitality.</p></article><article><span>02</span><h3>Discover</h3><p>Explore ideas through reading, hands-on learning, creative work, and the world around us.</p></article><article><span>03</span><h3>Encourage</h3><p>Bring what you know, share what you can, and help every family grow with confidence.</p></article></section>
      <section id="families" className="families section-shell"><div className="chapter"><span>For families</span><p>Come curious.</p></div><div><p className="eyebrow">A co-op shaped by its people</p><h2>Bring your questions, your gifts, and your kids.</h2><p className="large-copy">The village works because families learn and contribute alongside one another. Current enrollment, class choices, expectations, and welcome steps are shared directly with interested families.</p><a className="text-link" href={facebookUrl} target="_blank" rel="noreferrer">Ask about joining <span>→</span></a></div></section>
      <section id="calendar" className="calendar"><div className="section-shell calendar-inner"><div><p className="eyebrow">Our shared rhythm</p><h2>The year has a story. We write it together.</h2></div><div className="notice"><span>2026–27</span><h3>Community calendar</h3><p>The co-op maintains a working calendar and event schedule for participating families. For current gathering dates, class days, and location details, use the private group.</p><a href={facebookUrl} target="_blank" rel="noreferrer">See current events on Facebook →</a></div></div></section>
      <section id="resources" className="resources section-shell"><div className="resources-intro"><p className="eyebrow">Resources</p><h2>Useful things, shared generously.</h2><p>Curriculum materials, family guides, class information, and administrative documents live in the co-op’s shared Drive. Access is provided directly to participating families.</p></div><div className="resource-list"><div><span>01</span><h3>Curriculum</h3><p>Shared planning and class materials.</p></div><div><span>02</span><h3>Family guides</h3><p>Expectations and practical co-op information.</p></div><div><span>03</span><h3>Current schedules</h3><p>Working calendars and event details.</p></div></div></section>
      <section className="closing"><Image src="/veritas-lockup.png" alt="Veritas Village" width={520} height={270}/><h2>Come curious. Grow together.</h2><p>Connect with the private Veritas Village Co-op group for the most current information and a conversation about joining.</p><a className="button light" href={facebookUrl} target="_blank" rel="noreferrer">Connect on Facebook</a></section>
    </main><footer><Brand/><p>Learning in truth. Growing in community.</p><p>Central Texas</p></footer>
  </>;
}
