import Image from "next/image";
import PublicNews from "./public-news";
import FacebookGroupLink from "./facebook-group-link";
import { calendarSubscribeUrl, googleCalendarAddUrl } from "../lib/supabase";

export default function Home(){return <>
  <header className="site-header"><a href="#top" className="mini-brand" aria-label="Veritas Village"><Image src="/brand/lockup-horizontal-navy.png" alt="Veritas Village" width={900} height={310} priority/></a><nav aria-label="Main navigation"><a href="#welcome">Welcome</a><a href="#families">Families</a><a href="#rhythm">Our rhythm</a><a href="#resources">Resources</a><a href="#news">News</a></nav><a className="header-link" href="https://family.veritasvillage.org/family-village">Family sign in</a><details><summary>Menu</summary><div><a href="#welcome">Welcome</a><a href="#families">Families</a><a href="#rhythm">Our rhythm</a><a href="#resources">Resources</a><a href="#news">News</a><a href="https://family.veritasvillage.org/family-village">Family sign in</a></div></details></header>

  <main id="top">
    <section className="hero"><div className="hero-brand-row"><span aria-hidden="true"/><div className="hero-logo"><Image src="/brand/lockup-horizontal-navy.png" alt="Veritas Village" width={900} height={310} priority/></div><i aria-hidden="true">◆</i><span aria-hidden="true"/></div><p className="descriptor">A Central Texas homeschool co-op</p><h1>Learning in truth.<br/><em>Growing in community.</em></h1><p className="hero-copy">A welcoming place for families to learn alongside one another—rooted close to home and open to a wide world of wonder.</p><FacebookGroupLink className="primary-link">Meet the village <span>→</span></FacebookGroupLink><div className="scroll-note">Scroll to wander <i>↓</i></div></section>

    <section id="welcome" className="welcome"><div className="welcome-title"><span>Welcome</span><h2>There is room<br/>at the table.</h2></div><div className="welcome-copy"><p className="lead">Veritas Village is a parent-led cooperative education program for Central Texas homeschoolers.</p><p>We are a diverse, inclusive, volunteer-run 501(c)(3) offering academic, enrichment, and social opportunities in a classroom setting. Children find companions for discovery; parents share the work and encourage one another along the way.</p><p>Our yearlong studies center on history and science, with enrichment electives changing by semester according to the gifts parents bring.</p></div><div className="welcome-mark" aria-hidden="true">V</div></section>

    <section className="motto"><p>Grounded</p><i>◆</i><p>Curious</p><i>◆</i><p>Gracious</p><i>◆</i><p>Locally rooted</p></section>

    <section id="families" className="families"><div className="families-copy"><p className="eyebrow">For families</p><h2>Come curious.<br/>Bring what you know.</h2><p>Veritas Village serves learners from preschool through high school, with age groups adjusted when appropriate for a child’s needs and ability level.</p><p>One adult from each family remains on site and participates by teaching and assisting. Co-op events are not drop-off, and every participating adult and child must have a liability waiver on file.</p><a className="text-link" href="mailto:veritasvillagecoop@gmail.com">Ask about enrollment →</a></div><div className="family-panel facts"><p className="panel-label">At a glance</p><dl><div><dt>Age groups</dt><dd>Preschool through high school</dd></div><div><dt>School year</dt><dd>26 weeks</dd></div><div><dt>Family tuition</dt><dd>$300 per year</dd></div><div><dt>Student tuition</dt><dd>$150 per child, per year</dd></div><div><dt>Family role</dt><dd>Teach, assist, and stay on site</dd></div></dl><small>Enrollment and placement remain subject to availability and director approval.</small></div></section>

    <section id="rhythm" className="rhythm"><div className="rhythm-heading"><p className="eyebrow">Our shared rhythm</p><h2>A full day for<br/><em>learning together.</em></h2><p className="rhythm-intro">Our current co-op day runs from 9:45 AM setup through 3:15 PM departure, with additional gatherings able to grow beyond that weekly rhythm.</p></div><div className="day-flow"><div><time>9:45</time><span>Arrive + set up</span></div><div><time>10:00</time><span>History</span></div><div><time>11:00</time><span>Science</span></div><div><time>12:00</time><span>Lunch</span></div><div><time>1:00</time><span>Elective</span></div><div><time>2:00</time><span>Elective</span></div><div><time>3:00</time><span>Clean up</span></div></div><div className="calendar-note"><strong>2026–27 calendar</strong><p>Subscribe once and co-op dates show up in your own calendar app from then on.</p><span className="subscribe-link"><a className="compliance-cta ghost" href={calendarSubscribeUrl("scope=public")}>Subscribe to this calendar ↗</a><a className="compliance-cta ghost" href={googleCalendarAddUrl("scope=public")} target="_blank" rel="noreferrer">Add to Google Calendar ↗</a></span></div></section>

    <section id="resources" className="resources"><div><p className="eyebrow">The shared shelf</p><h2>Made useful.<br/>Kept together.</h2><p>Public connections live here. Family schedules, children’s classes, notes, photographs, and signed paperwork belong inside the invitation-only Family Village.</p><a className="portal-link" href="https://family.veritasvillage.org/family-village">Enter Family Village →</a></div><ul><li><span>Family Village</span><a href="https://family.veritasvillage.org/family-village">Private portal ↗</a></li><li><span>Member Facebook group</span><FacebookGroupLink>Open group ↗</FacebookGroupLink></li><li><span>Contact the co-op</span><a href="mailto:veritasvillagecoop@gmail.com">Send email ↗</a></li><li><span>Family handbook</span><small>Available privately when approved</small></li><li><span>Community calendar</span><a href={calendarSubscribeUrl("scope=public")}>Subscribe ↗</a></li></ul></section>

    <PublicNews />

    <section className="invitation"><div className="invitation-mark" aria-hidden="true">◆</div><p>Rooted in Central Texas. Open to wonder.</p><h2>Come as you are.</h2><span>Questions about enrollment, classes, or the co-op day?</span><a href="mailto:veritasvillagecoop@gmail.com">Email Veritas Village →</a></section>
  </main>
  <footer><span>Veritas Village</span><span>Learning in truth. Growing in community.</span><span>Central Texas</span><nav aria-label="Site policies"><a href="mailto:veritasvillagecoop@gmail.com?subject=Feedback%20on%20the%20website">Feedback</a><a href="/privacy">Privacy Policy</a><a href="/terms">Terms &amp; Conditions</a></nav></footer>
  </>}
