import { integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = {
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
};

export const users = sqliteTable("users", {
  id: text("id").primaryKey(), authSubject: text("auth_subject").notNull(), email: text("email").notNull(), displayName: text("display_name"), status: text("status", { enum: ["invited", "active", "suspended"] }).notNull().default("invited"), ...timestamps,
}, (table) => [uniqueIndex("idx_users_auth_subject").on(table.authSubject), uniqueIndex("idx_users_email").on(table.email)]);

export const families = sqliteTable("families", { id: text("id").primaryKey(), displayName: text("display_name").notNull(), ...timestamps });
export const familyMembers = sqliteTable("family_members", { id: text("id").primaryKey(), familyId: text("family_id").notNull(), userId: text("user_id").notNull(), relationship: text("relationship"), ...timestamps }, (table) => [uniqueIndex("idx_family_members_family_user").on(table.familyId, table.userId)]);
export const roles = sqliteTable("roles", { id: text("id").primaryKey(), userId: text("user_id").notNull(), role: text("role", { enum: ["parent", "teacher", "admin"] }).notNull(), ...timestamps }, (table) => [uniqueIndex("idx_roles_user_role").on(table.userId, table.role)]);
export const children = sqliteTable("children", { id: text("id").primaryKey(), familyId: text("family_id").notNull(), firstName: text("first_name").notNull(), lastInitial: text("last_initial"), ageBand: text("age_band"), active: integer("active", { mode: "boolean" }).notNull().default(true), ...timestamps });
export const classes = sqliteTable("classes", { id: text("id").primaryKey(), title: text("title").notNull(), description: text("description"), meetingTime: text("meeting_time"), term: text("term"), ...timestamps });
export const enrollments = sqliteTable("enrollments", { id: text("id").primaryKey(), classId: text("class_id").notNull(), childId: text("child_id").notNull(), status: text("status", { enum: ["active", "waitlisted", "withdrawn"] }).notNull().default("active"), ...timestamps }, (table) => [uniqueIndex("idx_enrollments_class_child").on(table.classId, table.childId)]);
export const teacherAssignments = sqliteTable("teacher_assignments", { id: text("id").primaryKey(), classId: text("class_id").notNull(), userId: text("user_id").notNull(), assignmentRole: text("assignment_role", { enum: ["lead", "assistant"] }).notNull(), ...timestamps }, (table) => [uniqueIndex("idx_teacher_assignments_class_user").on(table.classId, table.userId)]);
export const teacherNotes = sqliteTable("teacher_notes", { id: text("id").primaryKey(), childId: text("child_id").notNull(), classId: text("class_id").notNull(), authorUserId: text("author_user_id").notNull(), body: text("body").notNull(), visibility: text("visibility", { enum: ["family", "teachers", "admins"] }).notNull().default("family"), ...timestamps });
export const assignments = sqliteTable("assignments", { id: text("id").primaryKey(), classId: text("class_id").notNull(), title: text("title").notNull(), instructions: text("instructions"), dueAt: integer("due_at", { mode: "timestamp" }), publishedAt: integer("published_at", { mode: "timestamp" }), ...timestamps });
export const posts = sqliteTable("posts", { id: text("id").primaryKey(), authorUserId: text("author_user_id").notNull(), title: text("title").notNull(), body: text("body").notNull(), audience: text("audience", { enum: ["public", "families", "teachers", "class"] }).notNull(), classId: text("class_id"), publishedAt: integer("published_at", { mode: "timestamp" }), ...timestamps });
export const documents = sqliteTable("documents", { id: text("id").primaryKey(), familyId: text("family_id"), childId: text("child_id"), kind: text("kind").notNull(), title: text("title").notNull(), storageKey: text("storage_key").notNull(), signatureProvider: text("signature_provider"), signatureStatus: text("signature_status"), audience: text("audience", { enum: ["family", "teachers", "admins"] }).notNull().default("family"), ...timestamps });
export const media = sqliteTable("media", { id: text("id").primaryKey(), storageKey: text("storage_key").notNull(), title: text("title"), classId: text("class_id"), uploadedByUserId: text("uploaded_by_user_id").notNull(), audience: text("audience", { enum: ["family", "class", "coop"] }).notNull(), ...timestamps });
export const mediaConsents = sqliteTable("media_consents", { id: text("id").primaryKey(), mediaId: text("media_id").notNull(), childId: text("child_id").notNull(), approved: integer("approved", { mode: "boolean" }).notNull().default(false), approvedByUserId: text("approved_by_user_id"), ...timestamps }, (table) => [uniqueIndex("idx_media_consents_media_child").on(table.mediaId, table.childId)]);
export const events = sqliteTable("events", { id: text("id").primaryKey(), title: text("title").notNull(), description: text("description"), startsAt: integer("starts_at", { mode: "timestamp" }).notNull(), endsAt: integer("ends_at", { mode: "timestamp" }), location: text("location"), audience: text("audience", { enum: ["public", "families", "teachers", "class"] }).notNull(), classId: text("class_id"), ...timestamps });
export const invitations = sqliteTable("invitations", { id: text("id").primaryKey(), email: text("email").notNull(), familyId: text("family_id"), invitedByUserId: text("invited_by_user_id").notNull(), tokenHash: text("token_hash").notNull(), expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(), acceptedAt: integer("accepted_at", { mode: "timestamp" }), ...timestamps }, (table) => [uniqueIndex("idx_invitations_token_hash").on(table.tokenHash)]);
export const auditLog = sqliteTable("audit_log", { id: text("id").primaryKey(), actorUserId: text("actor_user_id").notNull(), action: text("action").notNull(), subjectType: text("subject_type").notNull(), subjectId: text("subject_id").notNull(), detail: text("detail"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
